### PR TITLE
Add: Bengali language 🇧🇩,🇮🇳 Guide 

### PR DESCRIPTION
**Pull request by imohitpatel**
Add the bengali(bangla) Bangladesh national language as well as indian state west Bengal native language to help 
Bangladeshi and indian people to more easily relate and understand this repo

### CODE REVIEW

**Comment by imohitpatel** [comment]
@YasinDehfuli please review and merge this PR

**Comment by YasinDehfuli** [comment]
Thanks dear @imohitpatel, but you need to translate all steps. You can analyze other pull requests and create a complete pull request for us.

**Comment by imohitpatel** [comment]
@YasinDehfuli ok 
Working on steps

**Comment by imohitpatel** [comment]
@YasinDehfuli please review and merged this PR

**Pull request merged**
